kafka-lag-exporter {
  port = 9999
  poll-interval = 5 seconds
  lookup-table-size = 120

  client-group-id = "kafka-lag-exporter"
  
  kafka-client-timeout = 10 seconds

  clusters = [
    {
      name = "realtime-cluster"
      bootstrap-brokers = "kafka:29092"
    }
  ]

  watchers = {
    strimzi = false
  }

  metric-whitelist = [
    "kafka_consumergroup_group_.*"
  ]
}

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
}

